name: Java CI
on:
  push:	
    branches:	
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Deploy to heroku using an action
        uses: akhileshns/heroku-deploy@v3.2.6
        with:
          heroku_api_key: "f687a341-d519-44fb-b5cb-2788967adc31"
          heroku_app_name: "shortline-app" #Must be unique in Heroku
          heroku_email: "sssimiao10@gmail.com"
